### ISSUE TITLE
Skipping unsuccessful mappings

### ISSUE THREAD

**Issue by BigAlKo** [sunshinejr/Moya-ModelMapper#57] opened 2018-04-19 19:13 UTC
Hello,

sometimes I need to skip unsuccessful mappings. For example I have a message model and get an array of messages from the server, which I want to map into an Array of message objects via Moya Modelmapper. I know the response shouldn't  response wrong values like in the example below (messageid 50), but in case if, I want to skip this message and go on. Actual my mapping ends in the catch-Block, and doesn't receive only the messages who are successful. 
Is there a possibility to skip these mappings, so that I can return a array only with message 1?

Here is my Example:

Response:
``` json
[ 
   { "messageid": 1,
     "sender": { "id": 1, ... },
     "message": "hello",
     "created": "2017-09-06T16:52:32.596Z"  
   }, 
   { "messageid": "50",
     "sender": { "id": 1, ... },
     "message": "hello",
     "created": "2017-09-06T16:52:32.596Z"  
   }
]
```

Model:
``` swift
class Message: Mappable {
  
  // MARK: - Stored Properties
  var messageId: Int
  var sender: User
  var message: String
  var created: Date
  
  // MARK: - Initializer
  required init(map: Mapper) throws {
    try messageID = map.from("messageid")
    try sender = map.from("sender")
    try message = map.from("message")
    try created = map.from("created", transformation: map.toDate)
  }
}
```

DataService:
``` swift

class DataService {

static func getMessages(userid: Int, success successCallback: @escaping successCallback, error errorCallback: @escaping errorCallback, failure failureCallback: @escaping failureCallback) {
    
    provider.request(.getMessages(userid: userid)) { (result) in
      
      switch result {
        case .success(let response):
          do {
            if response.statusCode >= 200 && response.statusCode <= 300 {
              let messages: [Message] = try response.map(to: [Message].self) // here I want to skip unsuccessful mappings and return a message array only with the successful mappings
              successCallback(messages)
            } else {
              errorCallback(Error.parsing(Class: "DataService", Method: "getMessages.else"))
            }
          } catch {
            // generate parsing error and send it to errorCallback
            errorCallback(Error.parsing(Class: "DataService", Method: "getMessages.catch"))
          }
        case .failure(let error):
          failureCallback(error)
        }
      }
    }
}
```

**Comment by sunshinejr** [comment] 2018-04-19 21:37
Hey @BigAlKo. So the issue is that our `map(_:)` function either maps the whole array or not. I wanted to add the function a function like `compactMap(_:)` that could remove the `nil` values. Actually I think that is a great idea, I'm gonna try to add it soon.

For now you could use the following instead:
```swift
guard let jsonArray = try response.mapJSON() as? [NSDictionary] else {
    throw MoyaError.jsonMapping(self)
}

do {
    return try jsonArray.flatMap { try? T(map: Mapper(JSON: $0)) } // or compactMap if Swift 4.1
} catch {
    throw MoyaError.underlying(error, self)
}
```

**Comment by sunshinejr** [comment] 2018-04-21 23:45
Hey @BigAlKo! Really happy to say that `compactMap` was introduced in `Moya-ModelMapper` 7.1.0! Gonna close this one, but if there is a problem with something in the future, don't hesitate to open a new ticket. Thanks so much again for the suggestion! 👍

**Closed by sunshinejr** 2018-04-21 23:45 UTC

**Comment by BigAlKo** [comment] 2018-04-24 09:55
Thank you, works like a charm! 🙌🏻
